=== andrefs/punuy-datasets/dataset-schema.json
{
  "$id": "https://andrefs.com/schemas/2023/SemRelDatasets",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "Domain": {
      "enum": ["biomedical", "emotional", "general", "geographical"],
      "type": "string"
    },
    "Language": {
      "enum": ["en", "pt"],
      "type": "string"
    },
    "LazyPartition": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "A description of the partition",
          "type": "string"
        },
        "id": {
          "description": "An identifier for the partition",
          "type": "string"
        },
        "metrics": {
          "additionalProperties": false,
          "description": "Evaluation metrics for the partition",
          "properties": {
            "annotators": {
              "additionalProperties": false,
              "description": "The number of annotators",
              "properties": {
                "fixedColumns": {
                  "description": "Whether each column in .values corresponds to a single annotator",
                  "type": "boolean"
                },
                "minEachPair": {
                  "description": "The minimum number of annotators for each pair",
                  "type": ["null", "number"]
                },
                "total": {
                  "description": "The total number of annotators",
                  "type": ["null", "number"]
                }
              },
              "required": ["minEachPair", "total"],
              "type": "object"
            },
            "interAnnoAgreement": {
              "description": "Inter annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            },
            "intraAnnoAgreement": {
              "description": "Intra annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            }
          },
          "required": ["annotators", "interAnnoAgreement"],
          "type": "object"
        },
        "origName": {
          "description": "Original name of the partition",
          "type": "string"
        },
        "relationType": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType",
          "description": "Which type of semantic relation is used to compare the words"
        },
        "scale": {
          "additionalProperties": false,
          "description": "The scale of the semantic relation values",
          "properties": {
            "value": {
              "additionalProperties": false,
              "description": "The scale for the .value property",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            },
            "values": {
              "additionalProperties": false,
              "description": "The scale for the .values property (if different from the .value scale)",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            }
          },
          "required": ["value"],
          "type": "object"
        }
      },
      "required": ["id", "metrics", "relationType", "scale"],
      "type": "object"
    },
    "License": {
      "additionalProperties": false,
      "properties": {
        "cannotRedistribute": {
          "description": "Whether the dataset can be redistributed",
          "type": "boolean"
        },
        "name": {
          "description": "The name of the license",
          "type": "string"
        },
        "url": {
          "description": "The URL of the license",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["name", "url"],
      "type": "object"
    },
    "Metadata": {
      "additionalProperties": false,
      "properties": {
        "authors": {
          "description": "The authors of the dataset\nExamples:\n- \"Jane Doe\"\n- \"Jane Doe, John Doe\"",
          "type": "string"
        },
        "date": {
          "description": "The date the dataset was published",
          "pattern": "^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$",
          "type": "string"
        },
        "description": {
          "description": "A description of the dataset",
          "type": "string"
        },
        "doi": {
          "description": "The DOI of the dataset",
          "pattern": "^10\\.[0-9]{4,}\\/.+$",
          "type": "string"
        },
        "domain": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Domain",
          "description": "The domain of the dataset"
        },
        "downloadUrls": {
          "description": "URL(s) to download the dataset files",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "languages": {
          "description": "The languages used in the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Language"
          },
          "type": "array"
        },
        "license": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/License",
          "description": "The license of the dataset"
        },
        "name": {
          "description": "The name of the dataset",
          "type": "string"
        },
        "nonOpen": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/NonOpen",
          "description": "Metadata for non-open datasets"
        },
        "papers": {
          "description": "Information about the scientific papers describing the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Paper"
          },
          "type": "array"
        },
        "relationTypes": {
          "description": "Which type of semantic relations are used to compare the words",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType"
          },
          "type": "array"
        },
        "tags": {
          "description": "Tags for the dataset content\nExamples:\n- mturk - the dataset was created using crowdsourcing (e.g. Amazon Mechanical Turk or CrowdFlower)\n- entities - the dataset contains entities (e.g. people, places, organizations)",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "urls": {
          "description": "Web sites containing information about the dataset",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "version": {
          "description": "The version of the dataset",
          "type": "string"
        }
      },
      "required": [
        "date",
        "description",
        "domain",
        "downloadUrls",
        "languages",
        "name",
        "papers",
        "relationTypes",
        "urls"
      ],
      "type": "object"
    },
    "NonOpen": {
      "additionalProperties": false,
      "properties": {
        "files": {
          "items": [
            {
              "additionalProperties": false,
              "properties": {
                "downloadUrl": {
                  "description": "The URL to download the file",
                  "format": "uri",
                  "type": "string"
                },
                "localFolderPath": {
                  "description": "The local folder path where the file should be stored",
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "origFileName": {
                  "description": "The name of the original file (for informative purposes only)",
                  "type": "string"
                },
                "partitionId": {
                  "description": "The id of the corresponding partition",
                  "type": "string"
                }
              },
              "required": ["downloadUrl", "localFolderPath", "partitionId"],
              "type": "object"
            }
          ],
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "isNonOpen": {
          "description": "Whether the dataset is non-open",
          "type": "boolean"
        }
      },
      "required": ["isNonOpen"],
      "type": "object"
    },
    "Paper": {
      "additionalProperties": false,
      "properties": {
        "title": {
          "description": "The title of the paper",
          "type": "string"
        },
        "url": {
          "description": "The URL where the paper can be found",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["title"],
      "type": "object"
    },
    "RelationType": {
      "enum": ["evocation", "relatedness", "similarity"],
      "type": "string"
    }
  },
  "properties": {
    "id": {
      "description": "An identifier for the dataset",
      "minLength": 3,
      "type": "string"
    },
    "metadata": {
      "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Metadata",
      "description": "Metadata for the dataset"
    },
    "originalInstructions": {
      "description": "The original instructions given to the annotators",
      "type": "string"
    },
    "partitions": {
      "items": {
        "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/LazyPartition"
      },
      "type": "array"
    }
  },
  "required": ["id", "metadata", "partitions"],
  "type": "object"
}

=== andrefs/punuy-datasets/profiles/rg65/dataset.json
{
  "id": "rg65",
  "metadata": {
    "name": "Rubenstein and Goodenough (1965)",
    "authors": "Herbert Rubenstein and John B. Goodenough",
    "urls": [
      "https://dl.acm.org/doi/pdf/10.1145/365628.365657"
    ],
    "papers": [
      {
        "title": " Contextual Correlates of Synonymy",
        "url": "https://dl.acm.org/doi/pdf/10.1145/365628.365657"
      }
    ],
    "date": "1965",
    "description": "",
    "downloadUrls": [
      "https://dl.acm.org/doi/pdf/10.1145/365628.365657"
    ],
    "languages": [
      "en"
    ],
    "domain": "general",
    "relationTypes": [
      "similarity"
    ]
  },
  "partitions": [
    {
      "id": "table1",
      "relationType": "similarity",
      "scale": {
        "value": {
          "min": 0.0,
          "max": 4.0
        }
      },
      "metrics": {
        "annotators": {
          "total": 51,
          "minEachPair": 51
        },
        "interAnnoAgreement": [
          {
            "metric": "pearson",
            "value": 0.99,
            "method": "other",
            "description": "A second group of 36 subjects (Group II) front the same general population as Group participated only in the second session but gave judgments on all 65 pairs. Accordingly for each of the 65 pairs of words judged by both groups of subjects in the second session a mean judgment was calculated for Groups I and iI independently. The correlation between these two sets of means came to r=.99."
          }
        ],
        "intraAnnoAgreement": [
          {
            "metric": "pearson",
            "value": 0.85,
            "method": "other"
          }
        ]
      }
    }
  ],
  "originalInstructions": "1. After looking through the whole deck, order the pairs according to amount of \"similarity of meaning\" so that the slip containing the pair exhibiting the greatest amount, of \"similarity of meaning\" is at the top of the deck and the pair exhibiting the least amount is on bottom.\n2. Assign a value from 4.0-0.0 to each pair -- the greater the \"similariby of meaning\", the higher the number. You may assign the same value to more than one pair.\n"
}

=== andrefs/punuy-datasets/profiles/mturk771/dataset.json
{
  "id": "mturk771",
  "metadata": {
    "name": "MTurk771",
    "authors": "Guy Halawi , Gideon Dror, Evgeniy Gabrilovich, Yehuda Koren",
    "urls": ["http://www2.mta.ac.il/~gideon/datasets/mturk_771.html"],
    "papers": [
      {
        "title": "Large-scale learning of word relatedness with constraints",
        "url": "https://www-ai.cs.tu-dortmund.de/LEHRE/FACHPROJEKT/WS1213/WordCorrelations.pdf"
      }
    ],
    "date": "2012",
    "description": "The set contains 771 word pairs along with their mean realtedness scores. The scores were collected on Amazon Mechanical Turk. At least 20 ratings were collected for each word pair, where each judgement task consisted of a batch of 50 word pairs. Ratings were collected on a 1-5 scale, where 5 stands for 'highly related' and 1 stands for 'not related'. In order to discard poor quality work, each batch contained 10 trap word pairs with known extreme relatedness values, serving as binary indicators. A batch that failed on more than one of the binary indicators was discarded. This guarantees an over 98% probability for detecting random workers (e.g., bots). The relatedness value of each word pair was taken as the mean score given by the workers.",
    "downloadUrls": [
      "http://www2.mta.ac.il/~gideon/datasets/MTURK-771-RAW.csv",
      "http://www2.mta.ac.il/~gideon/datasets/MTURK-771.csv"
    ],
    "relationTypes": ["relatedness"],
    "domain": "general",
    "languages": ["en"],
    "tags": ["mturk"]
  },
  "partitions": [
    {
      "id": "mturk",
      "relationType": "relatedness",
      "scale": {
        "value": {
          "min": 1,
          "max": 5
        },
        "values": {
          "min": 1,
          "max": 5
        }
      },
      "metrics": {
        "annotators": {
          "total": 115,
          "minEachPair": 20,
          "fixedColumns": false
        },
        "interAnnoAgreement": [
          {
            "method": "pearson",
            "value": 0.8957,
            "metric": "CBRGM",
            "description": "To verify the agreement between raters, following Snow et al. [21], we randomly split the raters into two groups, each including 10 Mechanical Turk workers. We then averaged the numeric judgements for each word pair among the raters in each of the two sets, thus yielding a (771 element long) vector of average judgments for each set. Finally, we computed the correlation between the vectors of the two sets. We repeated this process 1000 times, and over these 1000 random splits the mean correlation between the two sets of raters was 0.8957, with extremely small variance, attesting to the quality of the collected data"
          }
        ]
      }
    }
  ],
  "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/ws353Sim/dataset.json
{
  "id": "ws353Sim",
  "metadata": {
    "name": "WordSim-353 Similarity Gold Standard",
    "authors": "Eneko Agirre, Enrique Alfonseca, Keith Hall, Jana Kravalova, Marius Pasca, Aitor Soroa",
    "urls": [
      "http://alfonseca.org/eng/research/wordsim353.html"
    ],
    "papers": [
      {
        "title": "A Study on Similarity and Relatedness Using Distributional and WordNet-based Approaches",
        "url": "https://aclanthology.org/N09-1003.pdf"
      }
    ],
    "date": "2009",
    "description": "The final goldstandard for measuring similarity, in the same format as the WordSim353 distribution.",
    "downloadUrls": [
      "http://alfonseca.org/pubs/ws353simrel.tar.gz"
    ],
    "languages": [
      "en"
    ],
    "domain": "general",
    "relationTypes": [
      "similarity"
    ]
  },
  "partitions": [
    {
      "id": "wordsim_similarity_goldstandard",
      "relationType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 10
        }
      },
      "metrics": {
        "annotators": {
          "total": 29,
          "minEachPair": 13
        },
        "interAnnoAgreement": [
          {
            "method": "spearman",
            "value": 0.667,
            "metric": "unclear"
          }
        ]
      }
    }
  ],
  "originalInstructions": "Estimation of word similarity \n-----------------------------\n\n\nHello,\n\nWe kindly ask you to assist us in a psycholinguistic experiment, \naimed at estimating the similarity of various words in the English \nlanguage. The purpose of this experiment is to assign similarity scores \nto pairs of words, so that machine learning algorithms can be \nsubsequently trained and adjusted using human-assigned scores.\n\nBelow is a list of pairs of words. For each pair, please assign \na numerical similarity score between 0 and 10 (0 = words are totally \nunrelated, 10 = words are VERY closely related). By definition, \nthe similarity of the word to itself should be 10. You may assign \nfractional scores (for example, 7.5).\n\nSpecific instructions:\n\n1) The questionnaire starts on the next page.\n2) Please fill in your full name at the beginning of the questionnaire. \n   We need the names to ensure individual estimations do not get mixed, \n   and to be able to contact you should any clarifications become necessary.\n3) Please fill in the similarity scores in the appropriate column of \n   the table. To facilitate processing your questionnaire, please do not \n   print the document but rather type in the values in the table provided.\n4) If you do not know the meaning of a particular word - please use \n   a dictionary, or ask a native English speaker.\n5) Please DO NOT consult your friends on assigning the similarity scores  \n   it is highly important that the scores you assign be independent of \n   someone elses assessment.\n6) When estimating similarity of antonyms, consider them \"similar\"\n   (i.e., belonging to the same domain or representing features of the same \n   concept), rather than \"dissimilar\".\n\nIf you have any questions or require further clarifications (or if you \nhave a suggestion), please do not hesitate to contact us.\n\nThank you for your assistance !\n\n"
}

=== andrefs/punuy-datasets/profiles/mc30.json
{
  "id": "mc30",
  "metadata": {
    "name": "Miller and Charles (1991)",
    "urls": [],
    "papers": [
      {
        "title": "Contextual correlates of semantic similarity",
        "url": "https://sci-hub.se/https://doi.org/10.1080/01690969108406936"
      }
    ],
    "date": "1991",
    "description": "A total of 38 students at the State University of New York at Oswego participated as subjects. All of them were native speakers of English. A subset of 30 noun pairs from the original list of 65 studied by Rubenstein and Goodenough (1965) was used; 10 were selected from the high level (between 3 and 4 on a scale from 0 to 4), 10 from the intermediate level (between 1 and 3), and 10 from the low level (0 to 1) of semantic similarity.",
    "downloadUrls": [],
    "languages": ["en"],
    "domain": "general",
    "measureTypes": ["similarity"]
  },
  "partitions": [
    {
      "id": "table1",
      "measureType": "similarity",
      "scale": {
        "value": {
          "max": 4.0,
          "min": 0.0
        }
      },
      "metrics": {
        "annotators": {
          "total": 38,
          "minEachPair": 38
        },
        "interAgreement": {
          "pearson": 0.8848,
          "spearman": null
        }
      },
      "data": [
        {
          "term1": "car",
          "term2": "automobile",
          "value": 3.92
        },
        {
          "term1": "gem",
          "term2": "jewel",
          "value": 3.84
        },
        {
          "term1": "journey",
          "term2": "voyage",
          "value": 3.84
        },
        {
          "term1": "boy",
          "term2": "lad",
          "value": 3.76
        },
        {
          "term1": "coast",
          "term2": "shore",
          "value": 3.7
        },
        {
          "term1": "asylum",
          "term2": "madhouse",
          "value": 3.61
        },
        {
          "term1": "magician",
          "term2": "wizard",
          "value": 3.5
        },
        {
          "term1": "midday",
          "term2": "noon",
          "value": 3.42
        },
        {
          "term1": "furnace",
          "term2": "stove",
          "value": 3.11
        },
        {
          "term1": "food",
          "term2": "fruit",
          "value": 3.08
        },
        {
          "term1": "bird",
          "term2": "cock",
          "value": 3.05
        },
        {
          "term1": "bird",
          "term2": "crane",
          "value": 2.97
        },
        {
          "term1": "tool",
          "term2": "implement",
          "value": 2.95
        },
        {
          "term1": "brother",
          "term2": "monk",
          "value": 2.82
        },
        {
          "term1": "lad",
          "term2": "brother",
          "value": 1.66
        },
        {
          "term1": "crane",
          "term2": "implement",
          "value": 1.68
        },
        {
          "term1": "journey",
          "term2": "car",
          "value": 1.16
        },
        {
          "term1": "monk",
          "term2": "oracle",
          "value": 1.1
        },
        {
          "term1": "cemetery",
          "term2": "woodland",
          "value": 0.95
        },
        {
          "term1": "food",
          "term2": "rooster",
          "value": 0.89
        },
        {
          "term1": "coast",
          "term2": "hill",
          "value": 0.87
        },
        {
          "term1": "forest",
          "term2": "graveyard",
          "value": 0.84
        },
        {
          "term1": "shore",
          "term2": "woodland",
          "value": 0.63
        },
        {
          "term1": "monk",
          "term2": "slave",
          "value": 0.55
        },
        {
          "term1": "coast",
          "term2": "forest",
          "value": 0.42
        },
        {
          "term1": "lad",
          "term2": "wizard",
          "value": 0.42
        },
        {
          "term1": "chord",
          "term2": "smile",
          "value": 0.13
        },
        {
          "term1": "glass",
          "term2": "magician",
          "value": 0.11
        },
        {
          "term1": "rooster",
          "term2": "voyage",
          "value": 0.08
        },
        {
          "term1": "noon",
          "term2": "string",
          "value": 0.08
        }
      ]
    }
  ],
  "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/geresid50/dataset.json
{
  "id": "geresid50",
  "metadata": {
    "name": "GeReSiD",
    "urls": [
      "https://github.com/ucd-spatial/Datasets/tree/master/geresid-geo_relatedness_similarity_dataset"
    ],
    "papers": [
      {
        "title": "An Evaluative Baseline for Geo-Semantic Relatedness and Similarity",
        "url": "https://www.academia.edu/download/45239000/1402.3371.pdf"
      }
    ],
    "date": "2014",
    "description": "This dataset contains a-contextual semantic relatedness and similarity judgements on 50 pairs of geographic terms. For example, term pair motel and hotel have relatedness=0.93 and similarity=0.9. The dataset also contains the interrater agreement for each pair (e.g. 0.86 for relatedness, and 0.82 for similarity). The terms were selected from OpenStreetMap and are mapped to WordNet. The relatedness/similarity was collected from 203 human subjects on February 2012.",
    "downloadUrls": [
      "https://github.com/ucd-spatial/Datasets/blob/master/downloads/geresid-geo_relatedness_similarity_dataset.zip?raw=true"
    ],
    "languages": [
      "en"
    ],
    "domain": "geographical",
    "measureTypes": [
      "similarity",
      "relatedness"
    ]
  },
  "partitions": [
    {
      "id": "GeReSiD-rel",
      "measureType": "relatedness",
      "scale": {
        "value": {
          "max": 1,
          "min": 0
        }
      },
      "metrics": {
        "annotators": {
          "total": 81,
          "minEachPair": 81
        },
        "interAgreement": {
          "pearson": null,
          "spearman": 0.92
        }
      }
    },
    {
      "id": "GeReSiD-sim",
      "measureType": "similarity",
      "scale": {
        "value": {
          "max": 1,
          "min": 0
        }
      },
      "metrics": {
        "annotators": {
          "total": 122,
          "minEachPair": 122
        },
        "interAgreement": {
          "pearson": null,
          "spearman": 0.93
        }
      }
    }
  ],
  "originalInstructions": ""
}
