=== andrefs/punuy-datasets/dataset-schema.json
{
  "$id": "https://andrefs.com/schemas/2023/SemRelDatasets",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "Domain": {
      "enum": ["biomedical", "emotional", "general", "geographical"],
      "type": "string"
    },
    "Language": {
      "enum": ["en", "pt"],
      "type": "string"
    },
    "LazyPartition": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "A description of the partition",
          "type": "string"
        },
        "id": {
          "description": "An identifier for the partition",
          "type": "string"
        },
        "metrics": {
          "additionalProperties": false,
          "description": "Evaluation metrics for the partition",
          "properties": {
            "annotators": {
              "additionalProperties": false,
              "description": "The number of annotators",
              "properties": {
                "fixedColumns": {
                  "description": "Whether each column in .values corresponds to a single annotator",
                  "type": "boolean"
                },
                "minEachPair": {
                  "description": "The minimum number of annotators for each pair",
                  "type": ["null", "number"]
                },
                "total": {
                  "description": "The total number of annotators",
                  "type": ["null", "number"]
                }
              },
              "required": ["minEachPair", "total"],
              "type": "object"
            },
            "interAnnoAgreement": {
              "description": "Inter annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            },
            "intraAnnoAgreement": {
              "description": "Intra annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            }
          },
          "required": ["annotators", "interAnnoAgreement"],
          "type": "object"
        },
        "origName": {
          "description": "Original name of the partition",
          "type": "string"
        },
        "relationType": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType",
          "description": "Which type of semantic relation is used to compare the words"
        },
        "scale": {
          "additionalProperties": false,
          "description": "The scale of the semantic relation values",
          "properties": {
            "value": {
              "additionalProperties": false,
              "description": "The scale for the .value property",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            },
            "values": {
              "additionalProperties": false,
              "description": "The scale for the .values property (if different from the .value scale)",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            }
          },
          "required": ["value"],
          "type": "object"
        }
      },
      "required": ["id", "metrics", "relationType", "scale"],
      "type": "object"
    },
    "License": {
      "additionalProperties": false,
      "properties": {
        "cannotRedistribute": {
          "description": "Whether the dataset can be redistributed",
          "type": "boolean"
        },
        "name": {
          "description": "The name of the license",
          "type": "string"
        },
        "url": {
          "description": "The URL of the license",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["name", "url"],
      "type": "object"
    },
    "Metadata": {
      "additionalProperties": false,
      "properties": {
        "authors": {
          "description": "The authors of the dataset\nExamples:\n- \"Jane Doe\"\n- \"Jane Doe, John Doe\"",
          "type": "string"
        },
        "date": {
          "description": "The date the dataset was published",
          "pattern": "^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$",
          "type": "string"
        },
        "description": {
          "description": "A description of the dataset",
          "type": "string"
        },
        "doi": {
          "description": "The DOI of the dataset",
          "pattern": "^10\\.[0-9]{4,}\\/.+$",
          "type": "string"
        },
        "domain": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Domain",
          "description": "The domain of the dataset"
        },
        "downloadUrls": {
          "description": "URL(s) to download the dataset files",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "languages": {
          "description": "The languages used in the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Language"
          },
          "type": "array"
        },
        "license": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/License",
          "description": "The license of the dataset"
        },
        "name": {
          "description": "The name of the dataset",
          "type": "string"
        },
        "nonOpen": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/NonOpen",
          "description": "Metadata for non-open datasets"
        },
        "papers": {
          "description": "Information about the scientific papers describing the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Paper"
          },
          "type": "array"
        },
        "relationTypes": {
          "description": "Which type of semantic relations are used to compare the words",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType"
          },
          "type": "array"
        },
        "tags": {
          "description": "Tags for the dataset content\nExamples:\n- mturk - the dataset was created using crowdsourcing (e.g. Amazon Mechanical Turk or CrowdFlower)\n- entities - the dataset contains entities (e.g. people, places, organizations)",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "urls": {
          "description": "Web sites containing information about the dataset",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "version": {
          "description": "The version of the dataset",
          "type": "string"
        }
      },
      "required": [
        "date",
        "description",
        "domain",
        "downloadUrls",
        "languages",
        "name",
        "papers",
        "relationTypes",
        "urls"
      ],
      "type": "object"
    },
    "NonOpen": {
      "additionalProperties": false,
      "properties": {
        "files": {
          "items": [
            {
              "additionalProperties": false,
              "properties": {
                "downloadUrl": {
                  "description": "The URL to download the file",
                  "format": "uri",
                  "type": "string"
                },
                "localFolderPath": {
                  "description": "The local folder path where the file should be stored",
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "origFileName": {
                  "description": "The name of the original file (for informative purposes only)",
                  "type": "string"
                },
                "partitionId": {
                  "description": "The id of the corresponding partition",
                  "type": "string"
                }
              },
              "required": ["downloadUrl", "localFolderPath", "partitionId"],
              "type": "object"
            }
          ],
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "isNonOpen": {
          "description": "Whether the dataset is non-open",
          "type": "boolean"
        }
      },
      "required": ["isNonOpen"],
      "type": "object"
    },
    "Paper": {
      "additionalProperties": false,
      "properties": {
        "title": {
          "description": "The title of the paper",
          "type": "string"
        },
        "url": {
          "description": "The URL where the paper can be found",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["title"],
      "type": "object"
    },
    "RelationType": {
      "enum": ["evocation", "relatedness", "similarity"],
      "type": "string"
    }
  },
  "properties": {
    "id": {
      "description": "An identifier for the dataset",
      "minLength": 3,
      "type": "string"
    },
    "metadata": {
      "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Metadata",
      "description": "Metadata for the dataset"
    },
    "originalInstructions": {
      "description": "The original instructions given to the annotators",
      "type": "string"
    },
    "partitions": {
      "items": {
        "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/LazyPartition"
      },
      "type": "array"
    }
  },
  "required": ["id", "metadata", "partitions"],
  "type": "object"
}

=== andrefs/punuy-datasets/dist/profiles/pt65/dataset.json
{
    "id": "pt65",
    "metadata": {
        "name": "PT65",
        "authors": "Granada R., Trojahn C., Vieira R.",
        "urls": ["http://www.inf.pucrs.br/linatural/wikimodels/similarity.html"],
        "papers": [
            {
                "title": "Comparing Semantic Relatedness between Word Pairsin Portuguese Using Wikipedia",
                "url": "https://hal.science/hal-02089290/file/leitzkegranada_22675.pdf"
            }
        ],
        "date": "2014",
        "description": "Portuguese translation of the RG65 from Rubenstein and Goodenough (1965).",
        "downloadUrls": [
            "https://www.inf.pucrs.br/linatural/wordpress/recursos-e-ferramentas/lista-de-pares-de-palavras/"
        ],
        "languages": ["pt"],
        "domain": "general",
        "relationTypes": ["relatedness"]
    },
    "partitions": [
        {
            "id": "main",
            "relationType": "relatedness",
            "scale": {
                "value": {
                    "max": 4,
                    "min": 0
                }
            },
            "metrics": {
                "annotators": {
                    "total": 50,
                    "minEachPair": 50
                },
                "interAnnoAgreement": [
                    {
                        "method": "pearson",
                        "value": 0.71,
                        "metric": "unclear"
                    }
                ]
            }
        }
    ],
    "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/card660/dataset.json
{
  "id": "card660",
  "metadata": {
    "name": "Card-660",
    "authors": "M.T. Pilehvar, D. Kartsaklis, V. Prokhorov, and N. Collier",
    "urls": [
      "https://pilehvar.github.io/card-660/"
    ],
    "papers": [
      {
        "title": "Card-660: Cambridge Rare Word Dataset -- a Reliable Benchmark for Infrequent Word Representation Models",
        "url": "https://pilehvar.github.io/card-660/Card-660.pdf"
      }
    ],
    "date": "2018",
    "description": "Card-660 is a challenging, yet reliable, benchmark for the evaluation of subword and rare word representation techniques. The dataset provides multiple advantages over existing benchmarks, including a very high inter-annotator agreement (IAA) of around 0.90, which is substantially higher than that for existing rare word datasets (Stanford Rare Word Similarity, with an estimated IAA of 0.41).",
    "downloadUrls": [
      "https://pilehvar.github.io/card-660/card-660.zip"
    ],
    "languages": [
      "en"
    ],
    "domain": "general",
    "relationTypes": [
      "similarity"
    ]
  },
  "partitions": [
    {
      "id": "main",
      "relationType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 4
        },
        "values": {
          "min": 0,
          "max": 4
        }
      },
      "metrics": {
        "annotators": {
          "total": 8,
          "minEachPair": 8
        },
        "interAnnoAgreement": [
          {
            "metric": "pearson",
            "method": "APIAA",
            "value": 0.889
          },
          {
            "metric": "pearson",
            "method": "AMIAA",
            "value": 0.935
          },
          {
            "metric": "spearman",
            "method": "APIAA",
            "value": 0.931
          },
          {
            "metric": "spearman",
            "method": "AMIAA",
            "value": 0.889
          }
        ]
      }
    }
  ],
  "originalInstructions": "Card-660 Similarity Scale\\n============================\\n\\nGiven a pair of words, the task is to score their semantic similarity according to the following [0-4] rating scale:\\n\\n   (4)  synonyms\\n        The two words are different ways of referring to the same concept.\\n            automobile\\tcar\\n            cellphone\\tmobile\\n            monitor\\tscreen\\n\\n   (3)  similar\\n        The two words are of the same nature, but slightly different in details.\\n            car\\t\\ttruck\\n            table\\tdesk\\n            tiger\\tlion\\n\\n   (2)  related\\n        The two words are closely related but they are not similar in their nature.\\n            car\\t\\tdriver\\n            desk\\toffice\\n            writer\\tpen\\n\\n   (1)  same domain or slight relation\\n        The two words have distant relationship.\\n            car\\t\\ttarmac\\n            driver\\ttraffic\\n            desk\\temployee\\n\\n   (0)  completely unrelated\\n            car\\t\\tsky\\n            tea\\t\\tweather\\n            supervision\\tmilk\\n"
}

=== andrefs/punuy-datasets/dist/profiles/ps65/dataset.json
{
    "id": "ps65",
    "metadata": {
        "name": "Pirro and Seco (2008)",
        "authors": "Giuseppe Pirr√≥, Nuno Seco",
        "urls": [],
        "papers": [
            {
                "title": "Design, Implementation and Evaluation of a New Semantic Similarity Metric Combining Features and Intrinsic Information Content",
                "url": "https://dl.acm.org/doi/abs/10.1007/978-3-540-88873-4_25"
            }
        ],
        "date": "2008",
        "description": "",
        "downloadUrls": [
            "https://raw.githubusercontent.com/jjlastra/HESML/7a513929213777fe47b17dbfdfd8c96cb8cb3f5c/HESML_Library/WN_Datasets/PirroSeco_full_dataset.csv"
        ],
        "languages": ["en"],
        "domain": "general",
        "relationTypes": ["similarity"]
    },
    "partitions": [
        {
            "id": "main",
            "relationType": "similarity",
            "scale": {
                "value": {
                    "min": 0,
                    "max": 4
                }
            },
            "metrics": {
                "annotators": {
                    "total": 101,
                    "minEachPair": 101
                },
                "interAnnoAgreement": []
            }
        }
    ],
    "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/mesh2/dataset.json
{
  "id": "mesh2",
  "metadata": {
    "name": "MeSH2",
    "authors": "Euripides G.M. Petrakis, Giannis Varelas, Angelos Hliaoutakis, Paraskevi Raftopoulou",
    "urls": [
      "https://www.intelligence.tuc.gr/similarity/datasets.php",
      "https://www.intelligence.tuc.gr/similarity/datasets/MeSHDataset.pdf"
    ],
    "papers": [
      {
        "title": "Design and Evaluation of Semantic Similarity Measures for Concepts Stemming from the Same or Different Ontologies",
        "url": "https://users.uop.gr/~praftop/papers/pdf/wms06-PVHR.pdf"
      }
    ],
    "date": "2006",
    "description": "",
    "downloadUrls": [
      "https://www.intelligence.tuc.gr/similarity/datasets/MeSHDataset.pdf"
    ],
    "languages": ["en"],
    "domain": "biomedical",
    "relationTypes": ["similarity"]
  },
  "partitions": [
    {
      "id": "main",
      "relationType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 1
        }
      },
      "metrics": {
        "annotators": {
          "total": 8,
          "minEachPair": 8
        },
        "interAnnoAgreement": []
      }
    }
  ],
  "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/emocon/dataset.json
{
  "id": "emocon",
  "metadata": {
    "name": "Emotion concepts 2022",
    "authors": "Kwon, Mijin; Wager, Tor; Phillips, Jonathan",
    "license": {
      "name": "CC0 1.0 Universal",
      "url": "https://creativecommons.org/publicdomain/zero/1.0/"
    },
    "urls": [
      "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6DPPKH"
    ],
    "papers": [
      {
        "title": "Representations of emotion concepts: Comparison across pairwise, appraisal feature-based, and word embedding-based similarity spaces",
        "url": "https://escholarship.org/content/qt8vj3d366/qt8vj3d366.pdf"
      }
    ],
    "date": "2022",
    "description": "(...) we collected pairwise similarity and appraisal feature ratings for 58 different emotion concepts and then employed representational similarity analysis to investigate the overlap between people’s pairwise similarity judgments and emotion similarity in a 14-dimensional appraisal space and three word embedding spaces from two word2vec models (300 dimensions) and the newer GPT-3 model (12288 dimensions).",
    "downloadUrls": [
      "https://dataverse.harvard.edu/file.xhtml?fileId=6905415&version=2.0&toolType=PREVIEW"
    ],
    "languages": [
      "en"
    ],
    "domain": "emotional",
    "relationTypes": [
      "similarity"
    ],
    "tags": [
      "mturk",
      "emotion"
    ],
    "version": "2023-01-25"
  },
  "partitions": [
    {
      "id": "pairwise",
      "relationType": "similarity",
      "scale": {
        "value": {
          "max": 100,
          "min": 0
        },
        "values": {
          "max": 100,
          "min": 0
        }
      },
      "metrics": {
        "annotators": {
          "total": 839,
          "minEachPair": 4
        },
        "interAnnoAgreement": []
      }
    }
  ],
  "originalInstructions": ""
}

=== andrefs/punuy-datasets/dist/profiles/sstars13/dataset.json
{
    "id": "sstars13",
    "metadata": {
        "name": "Shooting-Stars",
        "license": {
            "name": "CC BY-ND 4.0",
            "url": "https://creativecommons.org/licenses/by-nd/4.0/"
        },
        "authors": "A. F. Santos, J. P. Leal",
        "urls": [
            "https://github.com/andrefs/grettir-datasets/blob/main/stars-2021115.txt"
        ],
        "papers": [
            {
                "title": "A game with a purpose for building crowdsourced semantic relations datasets for named entities",
                "url": "https://drive.google.com/file/d/1PNlPMH2lQx3BJI8kEAQjVeLoiezeY1x8/view"
            }
        ],
        "date": "2023",
        "description": "Pairs of music artists sorted by relatedness",
        "downloadUrls": [
            "https://raw.githubusercontent.com/andrefs/grettir-datasets/refs/heads/main/stars-2021115.txt"
        ],
        "languages": [
            "en"
        ],
        "domain": "general",
        "relationTypes": [
            "relatedness"
        ]
    },
    "partitions": [
        {
            "id": "main",
            "origName": "main",
            "relationType": "relatedness",
            "scale": {
                "value": {
                    "min": 1,
                    "max": 13
                }
            },
            "metrics": {
                "annotators": {
                    "total": 1001,
                    "minEachPair": null
                },
                "interAnnoAgreement": [
                    {
                        "metric": "pearson",
                        "value": 0.693,
                        "method": "other"
                    }
                ]
            }
        }
    ],
    "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/ws353/dataset.json
{
  "id": "ws353",
  "metadata": {
    "name": "WordSimilarity-353",
    "urls": [
      "https://www.cs.technion.ac.il/~gabr/resources/data/wordsim353/",
      "https://gabrilovich.com/resources/data/wordsim353/wordsim353.html"
    ],
    "papers": [
      {
        "title": "Placing Search in Context: The Concept Revisited",
        "url": "https://www.cs.tau.ac.il/~ruppin/p116-finkelstein.pdf"
      }
    ],
    "date": "2002",
    "description": "The WordSimilarity-353 Test Collection contains two sets of English word pairs along with human-assigned similarity judgements. The collection can be used to train and/or test computer algorithms implementing semantic similarity measures (i.e., algorithms that numerically estimate similarity of natural language words).",
    "downloadUrls": [
      "https://gabrilovich.com/resources/data/wordsim353/wordsim353.zip"
    ],
    "languages": ["en"],
    "domain": "general",
    "measureTypes": ["similarity"]
  },
  "partitions": [
    {
      "id": "set1",
      "measureType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 10
        },
        "values": {
          "min": 0,
          "max": 10
        }
      },
      "metrics": {
        "annotators": {
          "total": 13,
          "minEachPair": 13
        },
        "interAgreement": {
          "pearson": null,
          "spearman": null
        }
      }
    },
    {
      "id": "set2",
      "measureType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 10
        }
      },
      "metrics": {
        "annotators": {
          "total": 16,
          "minEachPair": 16
        },
        "interAgreement": {
          "pearson": null,
          "spearman": null
        }
      }
    },
    {
      "id": "combined",
      "measureType": "similarity",
      "scale": {
        "value": {
          "min": 0,
          "max": 10
        }
      },
      "metrics": {
        "annotators": {
          "total": 29,
          "minEachPair": 13
        },
        "interAgreement": {
          "pearson": null,
          "spearman": 0.611
        }
      }
    }
  ],
  "originalInstructions": "Estimation of word similarity \n-----------------------------\n\n\nHello,\n\nWe kindly ask you to assist us in a psycholinguistic experiment, \naimed at estimating the similarity of various words in the English \nlanguage. The purpose of this experiment is to assign similarity scores \nto pairs of words, so that machine learning algorithms can be \nsubsequently trained and adjusted using human-assigned scores.\n\nBelow is a list of pairs of words. For each pair, please assign \na numerical similarity score between 0 and 10 (0 = words are totally \nunrelated, 10 = words are VERY closely related). By definition, \nthe similarity of the word to itself should be 10. You may assign \nfractional scores (for example, 7.5).\n\nSpecific instructions:\n\n1) The questionnaire starts on the next page.\n2) Please fill in your full name at the beginning of the questionnaire. \n   We need the names to ensure individual estimations do not get mixed, \n   and to be able to contact you should any clarifications become necessary.\n3) Please fill in the similarity scores in the appropriate column of \n   the table. To facilitate processing your questionnaire, please do not \n   print the document but rather type in the values in the table provided.\n4) If you do not know the meaning of a particular word - please use \n   a dictionary, or ask a native English speaker.\n5) Please DO NOT consult your friends on assigning the similarity scores  \n   it is highly important that the scores you assign be independent of \n   someone elses assessment.\n6) When estimating similarity of antonyms, consider them \"similar\"\n   (i.e., belonging to the same domain or representing features of the same \n   concept), rather than \"dissimilar\".\n\nIf you have any questions or require further clarifications (or if you \nhave a suggestion), please do not hesitate to contact us.\n\nThank you for your assistance !\n\n"
}

=== andrefs/punuy-datasets/profiles/minimayoSRS/dataset.json
{
  "id": "minimayoSRS",
  "metadata": {
    "name": "MiniMayoSRS",
    "urls": [
      "https://conservancy.umn.edu/handle/11299/196265"
    ],
    "papers": [
      {
        "title": "Measures of semantic similarity and relatedness in the biomedical domain",
        "url": "https://www.sciencedirect.com/science/article/pii/S1532046406000645?via%3Dihub"
      }
    ],
    "date": "2007",
    "description": "A subset of 29 medical concept pairs manually rater by medical coders for semantic relatedness with high inter-rater agreement.",
    "downloadUrls": [
      "https://conservancy.umn.edu/bitstream/handle/11299/196265/MiniMayoSRS.csv?sequence=2&isAllowed=y"
    ],
    "languages": [
      "en"
    ],
    "domain": "biomedical",
    "measureTypes": [
      "relatedness"
    ]
  },
  "partitions": [
    {
      "id": "physicians",
      "measureType": "relatedness",
      "scale": {
        "value": {
          "min": 1,
          "max": 4
        }
      },
      "metrics": {
        "annotators": {
          "total": 3,
          "minEachPair": 3
        },
        "interAgreement": {
          "pearson": 0.68,
          "spearman": null
        }
      }
    },
    {
      "id": "coders",
      "measureType": "relatedness",
      "scale": {
        "value": {
          "min": 1,
          "max": 4
        }
      },
      "metrics": {
        "annotators": {
          "total": 9,
          "minEachPair": 9
        },
        "interAgreement": {
          "pearson": 0.78,
          "spearman": null
        }
      }
    }
  ],
  "originalInstructions": ""
}
