=== andrefs/punuy-datasets/dataset-schema.json
{
  "$id": "https://andrefs.com/schemas/2023/SemRelDatasets",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "Domain": {
      "enum": ["biomedical", "emotional", "general", "geographical"],
      "type": "string"
    },
    "Language": {
      "enum": ["en", "pt"],
      "type": "string"
    },
    "LazyPartition": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "A description of the partition",
          "type": "string"
        },
        "id": {
          "description": "An identifier for the partition",
          "type": "string"
        },
        "metrics": {
          "additionalProperties": false,
          "description": "Evaluation metrics for the partition",
          "properties": {
            "annotators": {
              "additionalProperties": false,
              "description": "The number of annotators",
              "properties": {
                "fixedColumns": {
                  "description": "Whether each column in .values corresponds to a single annotator",
                  "type": "boolean"
                },
                "minEachPair": {
                  "description": "The minimum number of annotators for each pair",
                  "type": ["null", "number"]
                },
                "total": {
                  "description": "The total number of annotators",
                  "type": ["null", "number"]
                }
              },
              "required": ["minEachPair", "total"],
              "type": "object"
            },
            "interAnnoAgreement": {
              "description": "Inter annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            },
            "intraAnnoAgreement": {
              "description": "Intra annotator agreement metrics",
              "items": {
                "additionalProperties": false,
                "properties": {
                  "description": {
                    "description": "A description of how the value is calculated, preferably quoted from the paper",
                    "type": "string"
                  },
                  "method": {
                    "description": "How the value was calculated:\n- APIAA: Average Pairwise Inter-Annotator Agreement\n- AMIAA: Average Mean Inter-Annotator Agreement\n- ARRGMA: Average Repeated Randomized Group Means Agreement\n- other: another method\n- unclear: the method was not described in the paper",
                    "enum": ["AMIAA", "APIAA", "ARRGMA", "other", "unclear"],
                    "type": "string"
                  },
                  "metric": {
                    "description": "The method used to calculate the correlation coefficient: Pearson's or Spearman's",
                    "enum": ["pearson", "spearman", "unclear"],
                    "type": "string"
                  },
                  "value": {
                    "description": "The value of the correlation coefficient",
                    "type": "number"
                  }
                },
                "required": ["method", "metric", "value"],
                "type": "object"
              },
              "type": "array"
            }
          },
          "required": ["annotators", "interAnnoAgreement"],
          "type": "object"
        },
        "origName": {
          "description": "Original name of the partition",
          "type": "string"
        },
        "relationType": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType",
          "description": "Which type of semantic relation is used to compare the words"
        },
        "scale": {
          "additionalProperties": false,
          "description": "The scale of the semantic relation values",
          "properties": {
            "value": {
              "additionalProperties": false,
              "description": "The scale for the .value property",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            },
            "values": {
              "additionalProperties": false,
              "description": "The scale for the .values property (if different from the .value scale)",
              "properties": {
                "max": {
                  "description": "The maximum value of the scale",
                  "minimum": 1,
                  "type": "number"
                },
                "min": {
                  "description": "The minimum value of the scale",
                  "type": "number"
                }
              },
              "required": ["max", "min"],
              "type": "object"
            }
          },
          "required": ["value"],
          "type": "object"
        }
      },
      "required": ["id", "metrics", "relationType", "scale"],
      "type": "object"
    },
    "License": {
      "additionalProperties": false,
      "properties": {
        "cannotRedistribute": {
          "description": "Whether the dataset can be redistributed",
          "type": "boolean"
        },
        "name": {
          "description": "The name of the license",
          "type": "string"
        },
        "url": {
          "description": "The URL of the license",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["name", "url"],
      "type": "object"
    },
    "Metadata": {
      "additionalProperties": false,
      "properties": {
        "authors": {
          "description": "The authors of the dataset\nExamples:\n- \"Jane Doe\"\n- \"Jane Doe, John Doe\"",
          "type": "string"
        },
        "date": {
          "description": "The date the dataset was published",
          "pattern": "^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$",
          "type": "string"
        },
        "description": {
          "description": "A description of the dataset",
          "type": "string"
        },
        "doi": {
          "description": "The DOI of the dataset",
          "pattern": "^10\\.[0-9]{4,}\\/.+$",
          "type": "string"
        },
        "domain": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Domain",
          "description": "The domain of the dataset"
        },
        "downloadUrls": {
          "description": "URL(s) to download the dataset files",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "languages": {
          "description": "The languages used in the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Language"
          },
          "type": "array"
        },
        "license": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/License",
          "description": "The license of the dataset"
        },
        "name": {
          "description": "The name of the dataset",
          "type": "string"
        },
        "nonOpen": {
          "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/NonOpen",
          "description": "Metadata for non-open datasets"
        },
        "papers": {
          "description": "Information about the scientific papers describing the dataset",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Paper"
          },
          "type": "array"
        },
        "relationTypes": {
          "description": "Which type of semantic relations are used to compare the words",
          "items": {
            "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/RelationType"
          },
          "type": "array"
        },
        "tags": {
          "description": "Tags for the dataset content\nExamples:\n- mturk - the dataset was created using crowdsourcing (e.g. Amazon Mechanical Turk or CrowdFlower)\n- entities - the dataset contains entities (e.g. people, places, organizations)",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "urls": {
          "description": "Web sites containing information about the dataset",
          "items": {
            "format": "uri",
            "type": "string"
          },
          "type": "array"
        },
        "version": {
          "description": "The version of the dataset",
          "type": "string"
        }
      },
      "required": [
        "date",
        "description",
        "domain",
        "downloadUrls",
        "languages",
        "name",
        "papers",
        "relationTypes",
        "urls"
      ],
      "type": "object"
    },
    "NonOpen": {
      "additionalProperties": false,
      "properties": {
        "files": {
          "items": [
            {
              "additionalProperties": false,
              "properties": {
                "downloadUrl": {
                  "description": "The URL to download the file",
                  "format": "uri",
                  "type": "string"
                },
                "localFolderPath": {
                  "description": "The local folder path where the file should be stored",
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "origFileName": {
                  "description": "The name of the original file (for informative purposes only)",
                  "type": "string"
                },
                "partitionId": {
                  "description": "The id of the corresponding partition",
                  "type": "string"
                }
              },
              "required": ["downloadUrl", "localFolderPath", "partitionId"],
              "type": "object"
            }
          ],
          "maxItems": 1,
          "minItems": 1,
          "type": "array"
        },
        "isNonOpen": {
          "description": "Whether the dataset is non-open",
          "type": "boolean"
        }
      },
      "required": ["isNonOpen"],
      "type": "object"
    },
    "Paper": {
      "additionalProperties": false,
      "properties": {
        "title": {
          "description": "The title of the paper",
          "type": "string"
        },
        "url": {
          "description": "The URL where the paper can be found",
          "format": "uri",
          "type": "string"
        }
      },
      "required": ["title"],
      "type": "object"
    },
    "RelationType": {
      "enum": ["evocation", "relatedness", "similarity"],
      "type": "string"
    }
  },
  "properties": {
    "id": {
      "description": "An identifier for the dataset",
      "minLength": 3,
      "type": "string"
    },
    "metadata": {
      "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/Metadata",
      "description": "Metadata for the dataset"
    },
    "originalInstructions": {
      "description": "The original instructions given to the annotators",
      "type": "string"
    },
    "partitions": {
      "items": {
        "$ref": "https://andrefs.com/schemas/2023/SemRelDatasets#/definitions/LazyPartition"
      },
      "type": "array"
    }
  },
  "required": ["id", "metadata", "partitions"],
  "type": "object"
}

=== andrefs/punuy-datasets/profiles/pap900/dataset.json
{
  "id": "pap900",
  "metadata": {
    "name": "PAP900",
    "license": {
      "name": "CC BY-ND 4.0",
      "url": "https://creativecommons.org/licenses/by-nd/4.0/"
    },
    "authors": "A. F. Santos, J. P. Leal, R. A. Alves, T. Jacques",
    "urls": ["https://github.com/andrefs/PAP900"],
    "papers": [],
    "date": "2024",
    "description": "PAP900 is a semantic relations dataset containing semantic relatedness and semantic similarity values for 900 affective words in Portuguese (Palavras Afectivas em Português).",
    "downloadUrls": ["https://github.com/andrefs/PAP900"],
    "languages": ["pt"],
    "domain": "emotional",
    "relationTypes": ["similarity", "relatedness"]
  },
  "partitions": [
    {
      "id": "sim",
      "origName": "similarity",
      "relationType": "similarity",
      "scale": {
        "value": {
          "max": 4.0,
          "min": 0.0
        }
      },
      "metrics": {
        "annotators": {
          "total": 206,
          "minEachPair": 31,
          "fixedColumns": true
        },
        "interAnnoAgreement": [
          {
            "metric": "pearson",
            "value": 0.558,
            "method": "APIAA"
          },
          {
            "metric": "pearson",
            "value": 0.757,
            "method": "AMIAA"
          }
        ]
      }
    },
    {
      "id": "rel",
      "origName": "relatedness",
      "relationType": "relatedness",
      "scale": {
        "value": {
          "max": 4.0,
          "min": 0.0
        }
      },
      "metrics": {
        "annotators": {
          "total": 206,
          "minEachPair": 30
        },
        "interAnnoAgreement": [
          {
            "metric": "pearson",
            "value": 0.439,
            "method": "APIAA"
          },
          {
            "metric": "pearson",
            "value": 0.675,
            "method": "AMIAA"
          }
        ]
      }
    }
  ],
  "originalInstructions": "# Similarity\n\nNas próximas secções deste questionário ser-lhe-á pedido que avalie quantitativamente,\nnuma escala, a intensidade da semelhança semântica entre pares de palavras afetivas.\nPor favor, antes de começar, leia atentamente a instrução e exemplos abaixo.\n\nA pergunta que lhe fazemos é: quão semelhantes são as duas palavras? Pares de palavras\npouco similares deverão ser pontuados com valores mais baixos, e pares de palavras\nmuito similares com valores mais altos.\n\nPor exemplo, as palavras esperto e inteligente partilham muitas semelhanças, tal como\nalegria e felicidade. Confiante partilha muitas semelhanças consigo mesmo. Feliz e\nlouco partilham algumas semelhanças. Já triste e divertido não são nada semelhantes.\n\n    esperto, inteligente: muita (4)\n    alegria, felicidade: total (5)\n    confiante, confiante: total (5)\n    feliz, louco: alguma (3)\n    triste, divertido: nenhuma (1)\n\n\n# Relatedness\n\nNas próximas secções deste questionário ser-lhe-á pedido que avalie quantitativamente,\nnuma escala, a intensidade do relacionamento semântico entre pares de palavras afetivas.\nPor favor, antes de começar, leia atentamente a instrução e exemplos abaixo.\n\nA pergunta que lhe fazemos é: quão relacionadas estão as duas palavras? Pares de palavras\npouco relacionadas deverão ser pontuados com valores mais baixos, e pares de palavras\nmuito relacionadas com valores mais altos. Repare que palavras opostas apresentam\nfrequentemente valores de relacionamento elevados.\n\nPor exemplo, as palavras modesto e esperto parecem pouco relacionadas. Já dissimular e\ndisfarçar parecem muito relacionadas. Confiante está muito relacionado consigo mesmo.\nEnquanto que violento e pacífico, sendo palavras opostas, são frequentemente relacionadas,\ntal como alegria e tristeza.\n\n    modesto, esperto: nenhum (1)\n    dissimular, disfarçar: pouco (2)\n    confiante, confiante: total (5)\n    violento, paçífico: muito (4)\n    alegria, tristeza: total (5)\n"
}

=== andrefs/punuy-datasets/profiles/minimayoSRS.json
{
  "id": "minimayoSRS",
  "metadata": {
    "name": "MiniMayoSRS",
    "urls": ["https://conservancy.umn.edu/handle/11299/196265"],
    "papers": [
      {
        "title": "Measures of semantic similarity and relatedness in the biomedical domain",
        "url": "https://www.sciencedirect.com/science/article/pii/S1532046406000645?via%3Dihub"
      }
    ],
    "date": "2007",
    "description": "A subset of 29 medical concept pairs manually rater by medical coders for semantic relatedness with high inter-rater agreement.",
    "downloadUrls": [
      "https://conservancy.umn.edu/bitstream/handle/11299/196265/MiniMayoSRS.csv?sequence=2&isAllowed=y"
    ],
    "measureTypes": ["relatedness"]
  },
  "partitions": [
    {
      "id": "physicians",
      "measureType": "relatedness",
      "interval": {
        "min": 1,
        "max": 4
      },
      "metrics": {
        "annotators": {
          "total": 3,
          "minEachPair": 3
        },
        "interAgreement": {
          "pearson": 0.68,
          "spearman": null
        }
      },
      "data": [
        {
          "value": 4,
          "term1": "Renal failure",
          "term2": "Kidney failure"
        },
        {
          "value": 3,
          "term1": "Abortion",
          "term2": "Miscarriage"
        },
        {
          "value": 3.3,
          "term1": "Heart",
          "term2": "Myocardium"
        },
        {
          "value": 3,
          "term1": "Stroke",
          "term2": "Infarct"
        },
        {
          "value": 3,
          "term1": "Delusion",
          "term2": "Schizophrenia"
        },
        {
          "value": 2.7,
          "term1": "Calcification",
          "term2": "Stenosis"
        },
        {
          "value": 2.7,
          "term1": "Tumor metastasis",
          "term2": "Adenocarcinoma"
        },
        {
          "value": 3,
          "term1": "Congestive heart failure",
          "term2": "Pulmonary edema"
        },
        {
          "value": 1.7,
          "term1": "Pulmonary fibrosis",
          "term2": "Malignant tumor of lung"
        },
        {
          "value": 2.3,
          "term1": "Diarrhea",
          "term2": "Stomach cramps"
        },
        {
          "value": 2.3,
          "term1": "Mitral stenosis",
          "term2": "Atrial fibrillation"
        },
        {
          "value": 2,
          "term1": "Brain tumor",
          "term2": "Intracranial hemorrhage"
        },
        {
          "value": 1.7,
          "term1": "Antibiotic",
          "term2": "Allergy"
        },
        {
          "value": 1.7,
          "term1": "Pulmonary embolus",
          "term2": "Myocardial infarction"
        },
        {
          "value": 2,
          "term1": "Carpal tunnel syndrome",
          "term2": "Osteoarthritis"
        },
        {
          "value": 2,
          "term1": "Rheumatoid arthritis",
          "term2": "Lupus"
        },
        {
          "value": 2,
          "term1": "Acne",
          "term2": "Syringe"
        },
        {
          "value": 2,
          "term1": "Diabetes mellitus",
          "term2": "Hypertension"
        },
        {
          "value": 1.7,
          "term1": "Cortisone",
          "term2": "Total knee replacement"
        },
        {
          "value": 1.3,
          "term1": "Cholangiocarcinoma",
          "term2": "Colonoscopy"
        },
        {
          "value": 1.3,
          "term1": "Lymphoid hyperplasia",
          "term2": "Laryngeal cancer"
        },
        {
          "value": 1,
          "term1": "Appendicitis",
          "term2": "Osteoporosis"
        },
        {
          "value": 1,
          "term1": "Depression",
          "term2": "Cellulitis"
        },
        {
          "value": 1,
          "term1": "Hyperlipidemia",
          "term2": "Tumor metastasis"
        },
        {
          "value": 1,
          "term1": "Multiple sclerosis",
          "term2": "Psychosis"
        },
        {
          "value": 1,
          "term1": "Peptic ulcer disease",
          "term2": "Myopia"
        },
        {
          "value": 1,
          "term1": "Rectal polyp",
          "term2": "Aorta"
        },
        {
          "value": 1,
          "term1": "Varicose vein",
          "term2": "Entire knee meniscus"
        },
        {
          "value": 1,
          "term1": "Xerostomia",
          "term2": "Alcoholic cirrhosis"
        }
      ]
    },
    {
      "id": "coders",
      "measureType": "relatedness",
      "interval": {
        "min": 1,
        "max": 4
      },
      "metrics": {
        "annotators": {
          "total": 9,
          "minEachPair": 9
        },
        "interAgreement": {
          "pearson": 0.78,
          "spearman": null
        }
      },
      "data": [
        {
          "value": 4,
          "term1": "Renal failure",
          "term2": "Kidney failure"
        },
        {
          "value": 3.3,
          "term1": "Abortion",
          "term2": "Miscarriage"
        },
        {
          "value": 3,
          "term1": "Heart",
          "term2": "Myocardium"
        },
        {
          "value": 2.8,
          "term1": "Stroke",
          "term2": "Infarct"
        },
        {
          "value": 2.2,
          "term1": "Delusion",
          "term2": "Schizophrenia"
        },
        {
          "value": 2,
          "term1": "Calcification",
          "term2": "Stenosis"
        },
        {
          "value": 1.8,
          "term1": "Tumor metastasis",
          "term2": "Adenocarcinoma"
        },
        {
          "value": 1.4,
          "term1": "Congestive heart failure",
          "term2": "Pulmonary edema"
        },
        {
          "value": 1.4,
          "term1": "Pulmonary fibrosis",
          "term2": "Malignant tumor of lung"
        },
        {
          "value": 1.3,
          "term1": "Diarrhea",
          "term2": "Stomach cramps"
        },
        {
          "value": 1.3,
          "term1": "Mitral stenosis",
          "term2": "Atrial fibrillation"
        },
        {
          "value": 1.3,
          "term1": "Brain tumor",
          "term2": "Intracranial hemorrhage"
        },
        {
          "value": 1.2,
          "term1": "Antibiotic",
          "term2": "Allergy"
        },
        {
          "value": 1.2,
          "term1": "Pulmonary embolus",
          "term2": "Myocardial infarction"
        },
        {
          "value": 1.1,
          "term1": "Carpal tunnel syndrome",
          "term2": "Osteoarthritis"
        },
        {
          "value": 1.1,
          "term1": "Rheumatoid arthritis",
          "term2": "Lupus"
        },
        {
          "value": 1,
          "term1": "Acne",
          "term2": "Syringe"
        },
        {
          "value": 1,
          "term1": "Diabetes mellitus",
          "term2": "Hypertension"
        },
        {
          "value": 1,
          "term1": "Cortisone",
          "term2": "Total knee replacement"
        },
        {
          "value": 1,
          "term1": "Cholangiocarcinoma",
          "term2": "Colonoscopy"
        },
        {
          "value": 1,
          "term1": "Lymphoid hyperplasia",
          "term2": "Laryngeal cancer"
        },
        {
          "value": 1,
          "term1": "Appendicitis",
          "term2": "Osteoporosis"
        },
        {
          "value": 1,
          "term1": "Depression",
          "term2": "Cellulitis"
        },
        {
          "value": 1,
          "term1": "Hyperlipidemia",
          "term2": "Tumor metastasis"
        },
        {
          "value": 1,
          "term1": "Multiple sclerosis",
          "term2": "Psychosis"
        },
        {
          "value": 1,
          "term1": "Peptic ulcer disease",
          "term2": "Myopia"
        },
        {
          "value": 1,
          "term1": "Rectal polyp",
          "term2": "Aorta"
        },
        {
          "value": 1,
          "term1": "Varicose vein",
          "term2": "Entire knee meniscus"
        },
        {
          "value": 1,
          "term1": "Xerostomia",
          "term2": "Alcoholic cirrhosis"
        }
      ]
    }
  ],
  "originalInstructions": ""
}

=== andrefs/punuy-datasets/profiles/multisimlex/dataset.json
{
  "id": "multisimlex",
  "metadata": {
    "name": "Multi-SimLex",
    "authors": "Ivan VuliÄ‡, Simon Baker, Edoardo Maria Ponti, Ulla Petti, Ira Leviant, Kelly Wing, Olga Majewska, Eden Bar, Matt Malone, Thierry Poibeau, Roi Reichart and Anna Korhonen",
    "urls": ["https://multisimlex.com/"],
    "papers": [
      {
        "title": "Multi-SimLex: A Large-Scale Evaluation of Multilingual and Cross-Lingual Lexical Semantic Similarity",
        "url": "https://multisimlex.com/Multi-SimLex-Paper.pdf"
      }
    ],
    "date": "2020",
    "description": "Multi-SimLex is a large-scale multilingual resource for lexical semantics. The current version of Multi-SimLex provides human judgments on the semantic similarity of word pairs for as many as 12 monolingual and 66 cross-lingual datasets. The languages covered are typologically diverse and represent both major languages (e.g., Mandarin Chinese, Spanish, Russian) and less-resourced ones (e.g., Welsh, Kiswahili). Each language dataset is annotated for the lexical relation of semantic similarity and contains 1,888 semantically aligned concept pairs, providing a representative coverage of word classes (nouns, verbs, adjectives, adverbs), frequency ranks, similarity intervals, lexical fields, and concreteness levels.",
    "downloadUrls": ["https://multisimlex.com/#download"],
    "languages": ["en"],
    "domain": "general",
    "relationTypes": ["similarity"]
  },
  "partitions": [
    {
      "id": "ENG",
      "relationType": "similarity",
      "scale": {
        "value": {
          "max": 6,
          "min": 0
        }
      },
      "metrics": {
        "annotators": {
          "total": 13,
          "minEachPair": 13
        },
        "interAnnoAgreement": [
          {
            "method": "spearman",
            "value": 0.698,
            "metric": "APIAA"
          },
          {
            "method": "spearman",
            "value": 0.794,
            "metric": "AMIAA"
          }
        ]
      }
    }
  ],
  "originalInstructions": "All annotators must be required to abide by the following instructions:\n\nEach annotator must assign an integer score between 0 and 6 (inclusive) indicating how semantically similar the two words in a given pair are. A score of 6 indicates very high similarity (i.e., perfect synonymy), while zero indicates no similarity.\n\nEach annotator must score the entire set of 1,888 pairs in the dataset. The pairs must not be shared between different annotators.\n\nAnnotators are able to break the workload over a period of approximately 2-3 weeks, and are able to use external sources (e.g. dictionaries, thesauri, WordNet) if required.\n\nAnnotators are kept anonymous, and are not able to communicate with each other during the annotation process."
}
